### ISSUE TITLE
camera zoom issue

### ISSUE THREAD

**Issue by kiashikun** [Emmie2105/steponmetesting#3]
something the camera doesn't seem to zoom in or out properly - something based on the z value of the camera; it's zooms to far in and behind the z value of of the map itself. either a. limit how much the camera zooms in fix w/ z or b. allocate zooming to the camera's scale/size rather than the z value

**Comment by Dreamman247** [comment]
I disabled it temporarily, it will just be a fixed camera position until I check it next week.
